[phases.setup]
nixPkgs = ["python311", "uv"]
aptPkgs = ["libstdc++6"]

[phases.install]
cmds = ["uv sync --frozen --no-dev"]

[start]
cmd = "uv run --project . celery -A app.core.celery_app:celery_app --workdir apps/api beat --loglevel=info"
