/**
 * Auto-generated by openapi-typescript — do not edit manually.
 * Run `pnpm gen:types` to regenerate.
 */
export interface paths {
  "/api/dashboard": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["UserStats"];
          };
        };
        401: {
          content: {
            "application/json": { detail: string };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    UserStats: {
      due_today: number;
      total_reviews: number;
      current_streak: number;
      recent: {
        token: string;
        interval_days: number;
        reviewed_at: string;
      }[];
      unseen_milestone: number | null;
    };
  };
}

export interface operations {}
